In [ ]:
#Code for importing the dataset:
import pandas as pd
data_set = pd.read_excel('covid_19.xlsx')
X = data_set.iloc[:, :-1].values
y = data_set.iloc[:, -1].values
print(X)

#Code for checking null values:
data_set.isnull()
#The output here is, false in the whole dataset in every column and row.



#main code
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

# Function for importing Dataset
def importdata():

    balance_data = pd.read_excel('covid_19.xlsx')      
    #The dataset length i.e, number of rows
    #print ("Dataset Length: ", len(balance_data))
    #The dataset shape i.e, number of rows and columns
    #print ("Dataset Shape: ", balance_data.shape)
    # dataset observations
    #print ("Dataset: ",balance_data.head())
    return balance_data
  
# Function to split the dataset
def splitdataset(balance_data):

    # Separating the target variable
    X = balance_data.values[:,:-1]
    Y = balance_data.values[:, -1]
    # Splitting the dataset into train and test
    X_train, X_test, y_train, y_test = train_test_split( 
    X, Y, test_size = 0.2, random_state = 100)
    return X, Y, X_train, X_test, y_train, y_test
      
# Function to perform training with giniIndex.
def train_using_gini(X_train, X_test, y_train):
  
    # Creating the classifier object
    clf_gini = DecisionTreeClassifier(criterion = "gini",
            random_state = 100,max_depth=3, min_samples_leaf=2)
  
    # Performing training
    clf_gini.fit(X_train, y_train)
    return clf_gini
      
# Function to perform training with entropy.
def train_using_entropy(X_train, X_test, y_train):
  
    # Decision tree with entropy
    clf_entropy = DecisionTreeClassifier(
            criterion = "entropy", random_state = 100,
            max_depth = 3, min_samples_leaf = 5)
    # Performing training
    clf_entropy.fit(X_train, y_train)
    return clf_entropy
  
# Function to make predictions
def prediction(X_test, clf_object):
  
    # Predicton on test with giniIndex
    y_pred = clf_object.predict(X_test)
    return y_pred
      
# Function to calculate accuracy
def cal_accuracy(y_test, y_pred): 

    #printing the accuracy
    accuracy_accquired =(accuracy_score(y_test,y_pred)) 
    print ("Accuracy : ",accuracy_accquired*100) 

    #printing the report
    print("Report : ",classification_report(y_test, y_pred)) 
# Driver code
def main():
      
    # Building Phase
    data = importdata()
    X, Y, X_train, X_test, y_train, y_test = splitdataset(data)
    clf_gini = train_using_gini(X_train, X_test, y_train)
    clf_entropy = train_using_entropy(X_train, X_test, y_train)
      
    # Operational Phase
    # Prediction of results using gini
    y_pred_gini = prediction(X_test, clf_gini)
    cal_accuracy(y_test, y_pred_gini)
      
    # Prediction of results using entropy
    y_pred_entropy = prediction(X_test, clf_entropy)

# Calling main function
if __name__=="__main__":
    main()



[[104.   8.   1. ...   3.   1.   8.]
 [101.   8.   0. ...   3.   1.   0.]
 [137.   8.   1. ...   3.   1.  13.]
 ...
 [  3.   1.   1. ...   3.   1.   0.]
 [ 24.   9.   1. ...   3.   1.   0.]
 [ 15.  27.   1. ...   3.   1.   0.]]
Accuracy :  95.95375722543352
Report :                precision    recall  f1-score   support

         0.0       0.98      0.97      0.98       152
         1.0       0.82      0.86      0.84        21

    accuracy                           0.96       173
   macro avg       0.90      0.92      0.91       173
weighted avg       0.96      0.96      0.96       173

